apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app
spec:
  replicas: 2  # Deploy 2 pods
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
        - name: streamlit-container
          image: my-streamlit-app  # Use local image
          imagePullPolicy: Never
          ports:
            - containerPort: 8501

---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  selector:
    app: streamlit
  ports:
    - protocol: TCP
      port: 80       # Exposed service port
      targetPort: 8501  # Container’s port
  type: LoadBalancer  # Exposes externally
